server:
  port: 8433
spring:
  datasource:
    url: jdbc:mysql://192.168.196.131:3306/SOS?
    username: root
    password: Hyong430Fbing
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect